server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 8192
  #添加路径信息
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.hostmysql}:3306/reggie
    username: root
    password: ${db.pw}
  mvc:
    dispatch-options-request: true
  #开发环境的设定
  profiles:
    active: dev
  servlet:
    #上传文件大小的限制
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  application:
    name: springdataredis_demo
  #Redis相关配置
  redis:
    host: ${db.hostredis}
    port: 6379
    #password: 123456
    database: 0 #操作的是0号数据库
    jedis:
      #Redis连接池配置
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #连接池最大阻塞等待时间
        max-idle: 4 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
#    filter:
#      order: 1  # 过滤器的执行顺序
#      name: myFilter  # 过滤器的名称
#      url-pattern: /*  # 过滤器拦截的 URL 路径模式
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#开启事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
#自定义配置
reggie:
  imgepath: ${path.lujin}
#  imgepath: D:\webcode\reggie_waimai\imge\
#阿里云配置
aliyun:
  oss:

    endpoint: https://oss-cn-beijing.aliyuncs.com
    #    accessKeyId: LTAI5tAQus6jtJ1M87WyjbVR
    #    accessKeySecret: LQoc7b4EjaKCQ2M5fgCdMdjsKFZIml
    accessKeyId: LTAI5tQR123CUiXd6VmYpGVx
    accessKeySecret: Hh2y9Re2i79ihM6l21oivX4fA76axy
    bucketName: cxkbalq01demo
    templateCode: SMS_288735054
#支付宝相关配置
#APPID
alipay:
  appId: 9021000135613476
  appPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC+3pMJE5QXYXYkG9NDRXEurj4lPyh5TK2CwComypKzS5pV501BGtsn9Lz3TJMtt7dNpwxzozEcZkAUG4aAuYgPvjCEcwZOWUJQPxbTTLiAAaso3qMr9fv4BN9jFbb/XlxQeG7QkiXvo/jhy/wRm65YyBhNNXWWFzaRInOxQd1CceocLfB8kyEDK128oPiKrPu0hoRNSyJVFKd6ADYgkmEE2DQz35QaQHEOmchmMIkte+Gsxi3EhlNNsSDNDEN5uC9TKBCBu1edgVYnfRrscZTT9iQ4QioNE5MBvducANXHbtE1PB3tXOKw96Ak2ZgTOVP0+3hpui2KnZMNpqolep7DAgMBAAECggEBAKGwr2J7AXMlDw3bvIY6Z30iAmdPL5xCRqKC47Jk3Q2iOCYZgaprc8hPXV0ps2yBO3k+0B+N2WazgAkIoFKf2RFtDnDFeEwa9UBBkbaCQbG+uB4xLI1rHn6msg6gMJv4db99pnJtvFFb2NR/FxRbi8COEXgml2wEUid0xgkdQLCtkpbM/qsDnnC4imNY6Xt+qxwbcKBezKxkx0wmS3pCO/W9oviATC+Jy55pLBTv2iTwP0DX8Mr+JOMoZc3vpstzBmO2zTxv9b5KWpHuRwILiJrtVZEy8nIpe7e1U3zuWUkALxHi75U5Qf0/SoDl/Zmxss6+39JeQyBeD5TOihXU7DECgYEA+EkIZmc+y5TIupZXVujKfv6yLrIS95zplwz9889tv0Bp3yGksWzx18Q8EHvhSy/52cPsw84DtbsqZ3gd6BHvrFufsWSn0r9e/f+r/FN/HBCJ3j9Lus7haS/w3/HuCnZVi2m2t0DGmNLmuA7dAIWn2dQoKZ1iXbrKuFB6/3/tPe0CgYEAxMzU0dKyjPKNyHQ6WwQOAQu2rBycKKOPHht6GC/vZnDXrw+msw3azJCulf7R8aLAB/W6K7CqeX0uGmKQZcZ8uVjXGO05zLeMQfvljTnTl7rBGzv1tSbPBl98fr98+l8jLU9FGM0G6gJb3bXCdkMe0u1UdmuhCeP6XNxU+mO/OW8CgYEAsQ7j/qMCFQw1WVp9Tm0UexwG1WYIQKyVqDKLp6L1EL5OweCsIhsfHE/ExbySHZxJARLHdZsk6iRfSQpPyX+A+9kbONYfGBuBEoGRlI+2xbzFlMhuqPl/phOaIxnUN4HL32+z7Vs0RSehgQCYehbWbHDvcz3ZOB5NEsPR8wK3nMECgYEAm2ucg1yfj/qaiH1p/Kk2GhNTH5e0p8+L3l4azXFF4qQpYeK9ZtkBO97jUigdS3SZrW+dqJVr/Ggk+cdvfEEGDSahMNlgdVFbnly+DAtoFILzsHto77iHdOQCIOM/Y0exMz5QNmbtF+/m9zBtNBKMDE5MDv2u/22hMqb7IYeW5FcCgYAcISyKPvg1Gk5lOw7wZqiCotF5XdRxrJZ/3htlTi73Vy2aDismjxLW+pO9nkgCyJwUtAqsTVTC2Kzqmb/Lx+RqUGoMV49ZGFcUceFsaD9wAmWbph3CRt0fdeLiN8nd/69jFAi70o3NqMnZUPY6xejrXQGDw6J9F69D3E3qheQk/Q== #开启公钥模式：点击查看中的公钥
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmbI0miKQ2AtxlUOjEZpnoJOepHM/aMdFT/91t7Xs8QK285Zj1NdMzyaTAkjlYA1ZV8htPO6rdGysgaEvfzl+q+YDzjuKiNRyDkcH4oq1xAcpQAw/S9W0Vrx1Rwjn6G/uUY6k35xpiYYhh/LlxBOWZDwx9kbuZCi2XFrQer4dV37sri3OWPfQRYZPBCApnqouKK0+HJGu+EIU9EW4tUyoZ9NxDzr7wKoSgx+3dZJaNSSknfPReiZoRCJGQa8E3LsfhHQo4YgKcZFbO3uxUzbTz1vt7FizhejT4v0VfnSn+EfpjrR8sAUPbQ1g9Wv4xuBCr/+st0y5vvQKk1TkagC9nQIDAQAB
  notifyUrl:
#启动nata内网穿透后命令提示框中的http地址，上面启动后保留的地址
# /alipay/notify为处理回调参数的接口地址
